(function (){
  var $editorContainer = $('.news-item-container'),
      $html_editor = $('#editor'),
      $css_editor = $('#csseditor'),
      $preview = $('#preview'),
      aceEditor,
      aceEditorCss,
      resizable = true,
      testMarkupCss="";
	  testMarkup="";
testMarkup += "<table id=\"header\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\n";
testMarkup += "   <tbody><tr>\n";
testMarkup += "    <td colspan=\"2\" background=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/templates\/template0008\/acdYVYVYfYZVYUbeWZRYdWRQUUSQaSaQ\/img_header1.jpg\" height=\"20\" valign=\"bottom\">    \n";
testMarkup += "        <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" width=\"665\" height=\"1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.338f1889253737ed371ae9104420a2a0\/\">Contact Us<\/a>&nbsp;&nbsp;\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.4a871880c089f6ed371ae9104420a2a0\/\">Home<\/a>\n";
testMarkup += "    <\/td>   \n";
testMarkup += "    <td rowspan=\"2\" bgcolor=\"#669933\" width=\"100%\">&nbsp;<\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.4a871880c089f6ed371ae9104420a2a0\/\"><img alt=\"Cricket Australia\" height=\"85\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/templates\/template0008\/acdYVYVYfYZVYUbeWZRYdWRQUUSQaSaQ\/img_header2-1.jpg\" width=\"301\" border=\"0\"><\/a><\/td>\n";
testMarkup += "    <td><img alt=\"\" height=\"85\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/templates\/template0008\/acdYVYVYfYZVYUbeWZRYdWRQUUSQaSaQ\/img_header2-2.jpg\" width=\"466\"><\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "<\/tbody><\/table>\n";
testMarkup += "<table id=\"container\" cellspacing=\"0\" border=\"1\">\n";
testMarkup += "   <tbody><tr>\n";
testMarkup += "    <td id=\"navigation\" valign=\"top\">\n";
testMarkup += "\n";
testMarkup += "   <!-- Begin Nav-Vert Area -->\n";
testMarkup += "   \n";
testMarkup += "   <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/templates\/template0003\/RSUSZZcVWVTXTXXeWZRYdWRQUUSQaSaQ\/img_EAE766.gif\" alt=\"\" height=\"6\" width=\"152\"><br>\n";
testMarkup += "   <table cellspacing=\"0\" id=\"priNav\">\n";
testMarkup += "\n";
testMarkup += "   <tbody><tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.c96a3b94865dec4f08d6718b4420a2a0\/\">Live Scores<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.5641ea044f0fbf1f08d6718b4420a2a0\/\">News<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.99ed81758ec1272f08d6718b4420a2a0\/\">Series<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.ad989ff275cf76be6918d6104420a2a0\/\">Fixtures<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.aeacd1a4770386be6918d6104420a2a0\/\">Profiles<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.0bee513ec3ce256e6918d6104420a2a0\/\">Inside Cricket Australia<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.61c4769eb446687e6918d6104420a2a0\/\">Spirit of Cricket<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/\">Media Centre<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.b724402e943956be6918d6104420a2a0\/\">Getting Involved<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "\n";
testMarkup += "   <tr>\n";
testMarkup += "    <td width=\"100%\" class=\"linkLVL1\">\n";
testMarkup += "        <a href=\"\/web\/20050105050831\/http:\/\/www.cricketstore.com.au\/\" target=\"ae6be0cb3fe596be6918d6104420a2a0\">Cricket Store<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "   \n";
testMarkup += "   <\/tbody><\/table>\n";
testMarkup += "    <\/td>\n";
testMarkup += "    <td id=\"content\" valign=\"top\">    \n";
testMarkup += "        <table cellspacing=\"0\" id=\"contentBody\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "            <td rowspan=\"2\"><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" width=\"1\" height=\"462\"><\/td>";
testMarkup += "            <td height=\"400\" valign=\"top\">\n";
testMarkup += "                \n";
testMarkup += "<table border=\"0\" cellspacing=\"0\" cellpadding=\"8\" width=\"100%\" height=\"240\">\n";
testMarkup += "\n";
testMarkup += "  <tbody><tr>\n";
testMarkup += "   \n";
testMarkup += "    <td width=\"85%\" valign=\"top\" align=\"left\">\n";
testMarkup += "  \n";
testMarkup += "      <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "          <td>\n";
testMarkup += "\n";
testMarkup += "<!-- Chrome (Lt Green Namable) portlet chrome for ICC ACC feature portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" cellpadding=\"1\" class=\"tableHome1\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>Tsunami Relief Match<\/th>            \n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>                \n";
testMarkup += "<\/table>\n";
testMarkup += "\n";
testMarkup += "		<table style=\"HEIGHT: 63px\" bordercolor=\"#000000\" width=\"514\"> <tbody> <tr> <td>&nbsp;<a href=\"\/web\/20050105050831\/http:\/\/www.worldvision.com.au\/\" target=\"_blank\"><img alt=\"\" src=\"\/web\/20050105050831im_\/http:\/\/wic042cx.server-web.com\/Static%20Files\/Logos\/Series\/ICC%20World%20XI%20v%20ACC%20XI.gif\" border=\"0\"><\/a><\/td> <td><\/td> <td><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.4e3cc5119ab4f1bcb33873ac25d62dbc\/\"><strong><font color=\"#606420\">Click here for the latest news<\/font><\/strong><\/a> on the tsunami relief cricket match between the ICC World XI and the ACC XI on January 10 in Melbourne.<\/td> <\/tr> <\/tbody> <\/table><br xmlns:util=\"com.vignette.ri.common.util\" xmlns:commonutil=\"com.epicentric.contentmanagement.connectors.cda\" xmlns:java=\"http:\/\/xml.apache.org\/xslt\/java\"><ul><\/ul>\n";
testMarkup += "\n";
testMarkup += "<!-- Chrome (Lt Green Namable) portlet chrome for ICC ACC feature portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Live Scores) portlet chrome for Live Scores portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome1\" width=\"100%\">\n";
testMarkup += "            <thead>\n";
testMarkup += "                <tr>\n";
testMarkup += "                    <th>Live Scores<\/th>\n";
testMarkup += "                    <th style=\"text-align:right\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.c96a3b94865dec4f08d6718b4420a2a0\/\">View Live Score Summary<\/a><\/th>\n";
testMarkup += "                <\/tr>\n";
testMarkup += "            <\/thead>\n";
testMarkup += "<\/table>            \n";
testMarkup += "\n";
testMarkup += "<!-- Live Scores Created ( $created.ts ) -->\n";
testMarkup += "    \n";
testMarkup += "                <table cellspacing=\"3\" class=\"tableHomeScore\" border=\"0\">        \n";
testMarkup += "            <tbody><tr>\n";
testMarkup += "                <td width=\"35\" valign=\"top\" rowspan=\"10\">\n";
testMarkup += "                                    <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" height=\"40\" width=\"30\">\n";
testMarkup += "                                <\/td>\n";
testMarkup += "                <td valign=\"top\" height=\"18\" colspan=\"2\"><strong>3 mobile Test Series Aus v Pak<\/strong><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "                        <tr>\n";
testMarkup += "                <td valign=\"top\" nowrap=\"true\">\n";
testMarkup += "                AUS 568 <strong>v<\/strong> PAK 9\/324  <span style=\"font-weight:normal;\">    (88.4 overs) <\/span>  and  304\n";
testMarkup += "                <\/td>\n";
testMarkup += "                <td valign=\"top\" style=\"padding-left:10px\" nowrap=\"true\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=cc55f0f1f810f0993d3afb1025d62dbc_ws_MX&amp;javax.portlet.prp_cc55f0f1f810f0993d3afb1025d62dbc_matchId=e9ef1120-fdd4-470e-a59c-10f7fd9544a8&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><img alt=\"Report and Scorecard\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_report.gif\" width=\"23\" align=\"absmiddle\" border=\"0\">Report&nbsp;&amp;&nbsp;Scorecard<\/a><\/td>            \n";
testMarkup += "            <\/tr>\n";
testMarkup += "                    <tr>\n";
testMarkup += "                <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_www_images\/static\/images\/spacer.gif\" height=\"1\" width=\"300\"><\/td>\n";
testMarkup += "                <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_www_images\/static\/images\/spacer.gif\" height=\"1\" width=\"1\"><\/td>            \n";
testMarkup += "            <\/tr>\n";
testMarkup += "        <\/tbody><\/table> \n";
testMarkup += "        <hr>\n";
testMarkup += "    \n";
testMarkup += "                <table cellspacing=\"3\" class=\"tableHomeScore\" border=\"0\">        \n";
testMarkup += "            <tbody><tr>\n";
testMarkup += "                <td width=\"35\" valign=\"top\" rowspan=\"10\">\n";
testMarkup += "                                    <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" height=\"40\" width=\"30\">\n";
testMarkup += "                                <\/td>\n";
testMarkup += "                <td valign=\"top\" height=\"18\" colspan=\"2\"><strong>Cricket Australia Cup<\/strong><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "                        <tr>\n";
testMarkup += "                <td valign=\"top\" nowrap=\"true\">\n";
testMarkup += "                SA 2ND XI 3\/231 <span style=\"font-weight:normal;\">(80 overs)<\/span> and  203 <strong>v<\/strong> TAS 2ND XI 384\n";
testMarkup += "                <\/td>\n";
testMarkup += "                <td valign=\"top\" style=\"padding-left:10px\" nowrap=\"true\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=cc55f0f1f810f0993d3afb1025d62dbc_ws_MX&amp;javax.portlet.prp_cc55f0f1f810f0993d3afb1025d62dbc_matchId=80727e7d-af67-4c91-836b-1e5ff4a1ee9d&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><img alt=\"Report and Scorecard\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_report.gif\" width=\"23\" align=\"absmiddle\" border=\"0\">Report&nbsp;&amp;&nbsp;Scorecard<\/a><\/td>            \n";
testMarkup += "            <\/tr>\n";
testMarkup += "                    <tr>\n";
testMarkup += "                <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_www_images\/static\/images\/spacer.gif\" height=\"1\" width=\"300\"><\/td>\n";
testMarkup += "                <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_www_images\/static\/images\/spacer.gif\" height=\"1\" width=\"1\"><\/td>           \n ";
testMarkup += "            <\/tr>\n";
testMarkup += "        <\/tbody><\/table> \n";
testMarkup += "        <hr>\n";
testMarkup += "    \n";
testMarkup += "                <table cellspacing=\"3\" class=\"tableHomeScore\" border=\"0\">       \n ";
testMarkup += "            <tbody><tr>\n";
testMarkup += "                <td width=\"35\" valign=\"top\" rowspan=\"10\">\n";
testMarkup += "                                    <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" height=\"40\" width=\"30\">\n";
testMarkup += "                                <\/td>\n";
testMarkup += "                <td valign=\"top\" height=\"18\" colspan=\"2\"><strong>Tour Match (Limited Overs)<\/strong><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "                        <tr>\n";
testMarkup += "                <td valign=\"top\" nowrap=\"true\">\n";
testMarkup += "                VIC <strong>v<\/strong> W.I. 4\/106<span style=\"font-weight:normal;\"> (21.3 overs)<\/span>\n";
testMarkup += "                <\/td>\n";
testMarkup += "                <td valign=\"top\" style=\"padding-left:10px\" nowrap=\"true\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=cc55f0f1f810f0993d3afb1025d62dbc_ws_MX&amp;javax.portlet.prp_cc55f0f1f810f0993d3afb1025d62dbc_matchId=8cb75c74-396a-43c5-8fe0-120f05b8e748&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><img alt=\"Report and Scorecard\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_report.gif\" width=\"23\" align=\"absmiddle\" border=\"0\">Report&nbsp;&amp;&nbsp;Scorecard<\/a><\/td>            \n";
testMarkup += "            <\/tr>\n";
testMarkup += "   \n ";
testMarkup += "            <tr>\n";
testMarkup += "                <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" height=\"1\" width=\"300\"><\/td>\n";
testMarkup += "                <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_spacer.gif\" height=\"1\" width=\"1\"><\/td>         \n   ";
testMarkup += "            <\/tr>\n";
testMarkup += "        <\/tbody><\/table>\n ";
testMarkup += "       \n ";
testMarkup += "<br>\n";
testMarkup += "<!-- Chrome (Live Scores) portlet chrome for Live Scores portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Latest News) portlet chrome for Non custom news display (home) portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome1\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>Latest News<\/th>\n";
testMarkup += "            <th style=\"text-align:right\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.5641ea044f0fbf1f08d6718b4420a2a0\/\">View All<\/a><\/th>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>                \n";
testMarkup += "<\/table>    \n";
testMarkup += "\n";
testMarkup += "<!-------------------- Begin Module Code (view) ---------------------->\n";
testMarkup += "\n";
testMarkup += "    <div class=\"epi\">    \n";
testMarkup += "        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n";
testMarkup += "               \n";
testMarkup += "            <tbody><tr>               \n ";
testMarkup += "            <td valign=\"top\">  \n ";
testMarkup += "\n";
testMarkup += "                <p><span style=\"color:#666\">5 January, 2005<\/span><br>\n";
testMarkup += "                 \n";
testMarkup += "                    <table cellspacing=\"1\" class=\"imgBox\" align=\"left\" style=\"width:181px\">\n";
testMarkup += "                        <tbody><tr>\n";
testMarkup += "                            <td><img src=\"\/web\/20050105050831im_\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Series%20shots\/3-mobile%20Test%20series%20Aus%20v%20Pak\/watson%20appeal.jpg\" height=\"130\" width=\"177\" alt=\"Shane Watson claims his first Test wicket\"><\/td>\n";
testMarkup += "                        <\/tr>\n";
testMarkup += "                       \n ";
testMarkup += "                        <tr>\n";
testMarkup += "                            <td class=\"caption\">Shane Watson claims his first Test wicket<\/td>\n";
testMarkup += "                        <\/tr>\n";
testMarkup += "                        <tr>\n";
testMarkup += "                            <td class=\"copyright\"><\/td>\n";
testMarkup += "                        <\/tr>\n";
testMarkup += "                                               \n ";
testMarkup += "                    <\/tbody><\/table>                   \n ";
testMarkup += "                    \n";
testMarkup += "                    <span class=\"headLink1\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Victory%20close%20for%20Australia&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Victory close for Australia<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                    \n";
testMarkup += "                        A middle-order collapse has seen Pakistan slump to 9-323 in the third Test against Australia at the SCG, the home side on the verge of a clean sweep of the three-Test series at tea. Asim Kamal (85 no) and tailender Mohammad Asif (12 no) combined for a valuable 53-run tenth wicket partnership.\n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Victory%20close%20for%20Australia&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                   \n ";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/storypublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>            \n";
testMarkup += "\n";
testMarkup += "            <tr>                \n";
testMarkup += "            <td valign=\"top\">   \n";
testMarkup += "\n";
testMarkup += "                <p><span style=\"color:#666\">5 January, 2005<\/span><br>\n";
testMarkup += "                  \n  ";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Lara%20leads%20Windies%20in%20one-day%20warm-up&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Lara leads Windies in one-day warm-up<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                   \n ";
testMarkup += "                        The West Indies have won the toss and chosen to bat in their tour opener against Victoria at MCG. The Windies are led by Brian Lara, with top-line batsmen Shivnarine Chanderpaul, Chris Gayle and Marlon Samuels all in the starting 11.\n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Lara%20leads%20Windies%20in%20one-day%20warm-up&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                    \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/storypublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>           \n ";
testMarkup += "\n";
testMarkup += "            <tr>                \n";
testMarkup += "            <td valign=\"top\">   \n";
testMarkup += "\n";
testMarkup += "                <p><span style=\"color:#666\">5 January, 2005<\/span><br>\n";
testMarkup += "                    \n";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Four%20replacements%20for%20Pakistan%20VB%20squad&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Four replacements for Pakistan VB squad<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                   \n ";
testMarkup += "                        Pakistan has added four new faces to its squad for the VB Series against Australia and West Indies. Azhar Mahmood, Mohammad Hafeez, Rao Iftikhar Anjum and Taufeeq Umar will arrive in time for the warm-up game against Australia A on 12 January. \n";
testMarkup += "\n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Four%20replacements%20for%20Pakistan%20VB%20squad&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                    \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/storypublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>            \n";
testMarkup += "\n";
testMarkup += "            <tr>                \n";
testMarkup += "            <td valign=\"top\">   \n";
testMarkup += "\n";
testMarkup += "                <p><span style=\"color:#666\">5 January, 2005<\/span><br>\n";
testMarkup += "                    \n";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Big%20lead%20building%20for%20Proteas&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Big lead building for Proteas<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                    \n";
testMarkup += "                        South Africa is in an almost unbeatable position after the third day of the third Test against England in Cape Town after building a lead of 462. England already faces a world record run chase if it is to pull off a miraculous victory and take a 2-0 series lead.\n";
testMarkup += "\n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Big%20lead%20building%20for%20Proteas&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                    \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/storypublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>            \n";
testMarkup += "\n";
testMarkup += "            <tr>                \n";
testMarkup += "            <td valign=\"top\">   \n";
testMarkup += "\n";
testMarkup += "                <p><span style=\"color:#666\">5 January, 2005<\/span><br>\n";
testMarkup += "                    \n";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Benefit%20match%20attracts%20strong%20response&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Benefit match attracts strong response<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                    \n";
testMarkup += "                        Cricket fans have embraced the tsunami victims benefit match to be played at the MCG next Monday with 20,000 tickets already sold. The match will feature a World XI and an Asian XI at one of the world's most famous cricket grounds.\n";
testMarkup += "\n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.4a871880c089f6ed371ae9104420a2a0\/?javax.portlet.tpst=803614c3b83d99e6ed499b1025d62dbc_ws_MX&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_viewID=content&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_docName=Benefit%20match%20attracts%20strong%20response&amp;javax.portlet.prp_803614c3b83d99e6ed499b1025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                    \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/storypublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>            \n";
testMarkup += "\n";
testMarkup += "        <tr>\n";
testMarkup += "            <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/storypublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "        <\/tr> \n";
testMarkup += "        <tr>\n";
testMarkup += "            <td><hr><\/td>\n";
testMarkup += "        <\/tr>     \n";
testMarkup += "   \n";
testMarkup += "        <\/tbody><\/table>\n";
testMarkup += "    <\/div>\n";
testMarkup += "<!--                          End Module Code                            -->\n";
testMarkup += "\n";
testMarkup += "<br>\n";
testMarkup += "<!-- Chrome (Latest News) portlet chrome for Non custom news display (home) portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Media Release Lt Green) portlet chrome for CA - Media Releases (MR Publisher) portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome1\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>Media Releases<\/th>\n";
testMarkup += "            <th style=\"text-align:right\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/\">View All<\/a><\/th>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>                \n";
testMarkup += "<\/table>    \n";
testMarkup += "\n";
testMarkup += "<!-------------------- Begin Module Code (view) ---------------------->\n";
testMarkup += "\n";
testMarkup += "    <div class=\"epi\">    \n";
testMarkup += "    \n";
testMarkup += "        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n";
testMarkup += "           \n ";
testMarkup += "                            <tbody><tr>\n";
testMarkup += "                                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/camediapublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "                            <\/tr>               \n";
testMarkup += "\n";
testMarkup += "                <tr>     \n";
testMarkup += "                    <td valign=\"top\">\n";
testMarkup += "\n";
testMarkup += "                                    <p><span style=\"color:#666\">4 January, 2005<\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <span class=\"headLink1\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/?javax.portlet.tpst=564a1abceda4354bd0db701025d62dbc_ws_MX&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_viewID=content&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_docName=MCC%20match%20information%20-%20Tsunami%20charity%20match&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">MCC match information - Tsunami charity match<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                    \n";
testMarkup += "                        The following information was released by the Melbourne Cricket Club (MCC) today in relation to the tsunami charity match on Monday 10 January at the MCG.                        \n ";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/?javax.portlet.tpst=564a1abceda4354bd0db701025d62dbc_ws_MX&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_viewID=content&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_docName=MCC%20match%20information%20-%20Tsunami%20charity%20match&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>";
testMarkup += "                      \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "           \n";
testMarkup += "                            <tr>\n";
testMarkup += "                                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/camediapublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"5\" alt=\"\"><\/td>\n";
testMarkup += "                            <\/tr>\n";
testMarkup += "                            <tr>\n";
testMarkup += "                                <td colspan=\"3\"><hr><\/td>\n";
testMarkup += "                            <\/tr>\n";
testMarkup += "                            <tr>\n";
testMarkup += "                                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/camediapublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"5\" alt=\"\"><\/td>\n";
testMarkup += "                            <\/tr>\n ";
testMarkup += "                \n";
testMarkup += "                <tr>     \n";
testMarkup += "                    <td valign=\"top\">\n";
testMarkup += "\n";
testMarkup += "                                    <p><span style=\"color:#666\">3 January, 2005<\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <span class=\"headLink1\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/?javax.portlet.tpst=564a1abceda4354bd0db701025d62dbc_ws_MX&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_viewID=content&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_docName=Tickets%20on%20sale%20midday%20tomorrow%20for%20Tsunami%20charity%20match&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Tickets on sale midday tomorrow for Tsunami charity match<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                    \n";
testMarkup += "                        Tickets for the 10 January World Cricket Tsunami Appeal fund-raising game at the Melbourne Cricket Ground (MCG) go on sale at ticketmaster7 outlets from midday tomorrow, Tuesday 4 January.                        \n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/?javax.portlet.tpst=564a1abceda4354bd0db701025d62dbc_ws_MX&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_viewID=content&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_docName=Tickets%20on%20sale%20midday%20tomorrow%20for%20Tsunami%20charity%20match&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                      \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            \n";
testMarkup += "                            <tr>\n";
testMarkup += "                                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/camediapublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"5\" alt=\"\"><\/td>\n";
testMarkup += "                            <\/tr>\n";
testMarkup += "                            <tr>\n";
testMarkup += "                                <td colspan=\"3\"><hr><\/td>\n";
testMarkup += "                            <\/tr>\n";
testMarkup += "                            <tr>\n";
testMarkup += "                                <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/camediapublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"5\" alt=\"\"><\/td>\n";
testMarkup += "                            <\/tr> \n";
testMarkup += "                \n";
testMarkup += "\n";
testMarkup += "                <tr>     \n";
testMarkup += "                    <td valign=\"top\">\n";
testMarkup += "\n";
testMarkup += "                                <p><span style=\"color:#666\">1 January, 2005<\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <span class=\"headLink1\"><a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/?javax.portlet.tpst=564a1abceda4354bd0db701025d62dbc_ws_MX&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_viewID=content&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_docName=Melbourne%20pitches%20in%20to%20make%20MCG%20tsunami%20relief%20cricket%20match%20possible&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\">Melbourne pitches in to make MCG tsunami relief cricket match possible<\/a><\/span><br>\n";
testMarkup += "\n";
testMarkup += "                    <!-- Insert Object Abstract -->\n";
testMarkup += "                    \n";
testMarkup += "                        Australian cricket officials today called on Melbourne cricket fans to try to fill the MCG to its 80,000 seat capacity when a 10 January international cricket match is played as a World Vision tsunami relief fund raiser.                        \n";
testMarkup += "                        <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/template.MAXIMIZE\/menuitem.26d58ed38fdc797e6918d6104420a2a0\/?javax.portlet.tpst=564a1abceda4354bd0db701025d62dbc_ws_MX&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_viewID=content&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_docName=Melbourne%20pitches%20in%20to%20make%20MCG%20tsunami%20relief%20cricket%20match%20possible&amp;javax.portlet.prp_564a1abceda4354bd0db701025d62dbc_folderPath=%2Fv7%2Fcricketaustralia%2FHomepage%2F&amp;javax.portlet.begCacheTok=token&amp;javax.portlet.endCacheTok=token\"><u>More<\/u><\/a>\n";
testMarkup += "                      \n";
testMarkup += "                <\/p><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "\n";
testMarkup += "        <tr>\n";
testMarkup += "            <td colspan=\"3\"> <img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/camediapublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "        <\/tr> \n";
testMarkup += "        <tr>\n";
testMarkup += "            <td><hr><\/td>\n";
testMarkup += "        <\/tr>     \n";
testMarkup += "        \n";
testMarkup += "        <\/tbody><\/table>\n";
testMarkup += "    <\/div>\n";
testMarkup += "<!--                          End Module Code                            -->\n";
testMarkup += "\n";
testMarkup += "<br>\n";
testMarkup += "<!-- Chrome (Media Release Lt Green) portlet chrome for CA - Media Releases (MR Publisher) portlet - end -->\n";
testMarkup += "\n";
testMarkup += "          <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "      <\/tbody><\/table>\n";
testMarkup += "    <\/td>\n";
testMarkup += "\n";
testMarkup += "      <!-- horizontal spacer between div\/column layouts - begins -->\n";
testMarkup += "\n";
testMarkup += "      <!-- horizontal spacer between div\/column layouts - ends -->\n";
testMarkup += "\n";
testMarkup += "    <td width=\"15%\" valign=\"top\" align=\"left\">\n";
testMarkup += "  \n";
testMarkup += "      <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "          <td>\n";
testMarkup += "\n";
testMarkup += "<iframe marginwidth=\"0\" marginheight=\"0\" src=\"\/web\/20050105050831if_\/http:\/\/ad.au.doubleclick.net\/adi\/N1405.cricket\/B1480907.2;sz=180x150;ord=%5Btimestamp%5D\" frameborder=\"0\" width=\"180\" scrolling=\"no\" height=\"150\" bordercolor=\"#000000\">\n";
testMarkup += "&lt;SCRIPT language='JavaScript1.1' SRC=\"\/web\/20050105050831js_\/http:\/\/ad.au.doubleclick.net\/adj\/N1405.cricket\/B1480907.2;abr=!ie;sz=180x150;ord=%5Btimestamp%5D\"&gt;\n";
testMarkup += "&lt;\/SCRIPT&gt;\n";
testMarkup += "&lt;NOSCRIPT&gt;\n";
testMarkup += "&lt;A HREF=\"\/web\/20050105050831\/http:\/\/ad.au.doubleclick.net\/jump\/N1405.cricket\/B1480907.2;abr=!ie4;abr=!ie5;sz=180x150;ord=%5Btimestamp%5D\"&gt;\n";
testMarkup += "&lt;IMG SRC=\"\/web\/20050105050831im_\/http:\/\/ad.au.doubleclick.net\/ad\/N1405.cricket\/B1480907.2;abr=!ie4;abr=!ie5;sz=180x150;ord=%5Btimestamp%5D\" BORDER=0 WIDTH=180 HEIGHT=150 ALT=\"Click Here\"&gt;&lt;\/A&gt;\n";
testMarkup += "&lt;\/NOSCRIPT&gt;\n";
testMarkup += "<\/iframe>\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for CA - Audio Homepage portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome2\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>Latest Audio<\/th>            \n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>               \n ";
testMarkup += "<\/table>    \n";
testMarkup += "\n";
testMarkup += "    <table width=\"199\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "            <td valign=\"top\" width=\"199\" bgcolor=\"#ebebeb\">    \n";
testMarkup += "            \n";
testMarkup += "    <div class=\"epi\">    \n";
testMarkup += "        <table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"0\">\n";
testMarkup += "            <tbody><tr>\n";
testMarkup += "                <td>&nbsp;<\/td>\n";
testMarkup += "                <td><span style=\"color:#666\">Click to listen or right-mouse click to save to your PC<\/span><br><br><\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            \n";
testMarkup += "            <tr>     \n";
testMarkup += "                <td width=\"31\" valign=\"top\" nowrap=\"true\">    \n";
testMarkup += "                    <a href=\"\/web\/20050105050831\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Sportal%20audio\/January%202005\/gilchrist_113.mp3\" target=\"_blank\">\n";
testMarkup += "			<img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"7\" height=\"18\" alt=\"\" border=\"0\"><img width=\"23\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_audio_trans.gif\" border=\"0\">                    \n";
testMarkup += "                    <\/a>                        \n";
testMarkup += "                <\/td>\n";
testMarkup += "                <td>\n";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Sportal%20audio\/January%202005\/gilchrist_113.mp3\" target=\"_blank\">Adam Gilchrist on his 113 against Pakistan<\/a> <br>(3.23 MB, 3 min 09) <\/span><br>\n";
testMarkup += "                    <span style=\"color:#666\">4 January, 2005<\/span>\n";
testMarkup += "                    <!-- com.epicentric.contentmanagement.connectors.cda.util.ContentUtils.getStaticFileURL(\"cda\",$filePath) -->\n";
testMarkup += "                <\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"2\"><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>                 \n";
testMarkup += "           \n ";
testMarkup += "            <tr>     \n";
testMarkup += "                <td width=\"31\" valign=\"top\" nowrap=\"true\">    \n";
testMarkup += "                    <a href=\"\/web\/20050105050831\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Sportal%20audio\/January%202005\/ponting_155.mp3\" target=\"_blank\">\n";
testMarkup += "			<img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"7\" height=\"18\" alt=\"\" border=\"0\"><img width=\"23\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_audio_trans.gif\" border=\"0\">                    \n";
testMarkup += "                    <\/a>                        \n";
testMarkup += "                <\/td>\n";
testMarkup += "                <td>\n";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Sportal%20audio\/January%202005\/ponting_155.mp3\" target=\"_blank\">Ricky Ponting on his unbeaten 155 at the SCG<\/a> <br>(2.00 MB, 2 min 11) <\/span><br>\n";
testMarkup += "                    <span style=\"color:#666\">3 January, 2005<\/span>\n";
testMarkup += "                    <!-- com.epicentric.contentmanagement.connectors.cda.util.ContentUtils.getStaticFileURL(\"cda\",$filePath) -->\n";
testMarkup += "                <\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"2\"><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>                \n ";
testMarkup += "            \n";
testMarkup += "            <tr>     \n";
testMarkup += "                <td width=\"31\" valign=\"top\" nowrap=\"true\">    \n";
testMarkup += "                    <a href=\"\/web\/20050105050831\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Sportal%20audio\/January%202005\/stuart%20macgill%2002-01-2005.mp3\" target=\"_blank\">\n";
testMarkup += "			<img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"7\" height=\"18\" alt=\"\" border=\"0\"><img width=\"23\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_audio_trans.gif\" border=\"0\">                    \n";
testMarkup += "                    <\/a>                        \n";
testMarkup += "                <\/td>\n";
testMarkup += "                <td>\n";
testMarkup += "                    <span class=\"headLink2\"><a href=\"\/web\/20050105050831\/http:\/\/wic042cx.server-web.com\/\/Static%20Files\/Sportal%20audio\/January%202005\/stuart%20macgill%2002-01-2005.mp3\" target=\"_blank\">Stuart MacGill on his day one SCG efforts<\/a> <br>(1.83 MB, 1 min 57) <\/span><br>\n";
testMarkup += "                    <span style=\"color:#666\">2 January, 2005<\/span>\n";
testMarkup += "                    <!-- com.epicentric.contentmanagement.connectors.cda.util.ContentUtils.getStaticFileURL(\"cda\",$filePath) -->\n";
testMarkup += "                <\/td>\n";
testMarkup += "            <\/tr>\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"2\"><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"1\" height=\"10\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>                 \n";
testMarkup += "\n";
testMarkup += "            <tr>\n";
testMarkup += "                <td colspan=\"2\"><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/beans\/caaudiovideopublisher\/jsp\/images\/spacer.gif\" width=\"197\" height=\"1\" alt=\"\"><\/td>\n";
testMarkup += "            <\/tr>      \n";
testMarkup += "        <\/tbody><\/table>\n";
testMarkup += "    <\/div>\n";
testMarkup += "\n";
testMarkup += "            <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/tbody><\/table>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for CA - Audio Homepage portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for Pura Cup Points Table 2004\/05 portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome2\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>Pura Cup Points Table<\/th>            \n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>                \n";
testMarkup += "<\/table>    \n";
testMarkup += "\n";
testMarkup += "    <table width=\"199\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "            <td valign=\"top\" width=\"199\" bgcolor=\"#ebebeb\">    \n";
testMarkup += "            \n";
testMarkup += "		<i>Current at&nbsp;Dec 22, 2004<\/i>&nbsp;<br> <table style=\"HEIGHT: 170px\" cellspacing=\"0\" cellpadding=\"0\" width=\"163\" align=\"center\" border=\"0\"> <tbody> <tr> <td style=\"HEIGHT: 20px\" width=\"100\"><b>TEAM<\/b><\/td> <td style=\"HEIGHT: 20px\" width=\"100\"><b>Mt<\/b><\/td> <td style=\"HEIGHT: 20px\" width=\"100\"><b>Pts<\/b><\/td> <td style=\"HEIGHT: 20px\" width=\"100\"><b>Qt<\/b><\/td> <\/tr> <tr> <td style=\"HEIGHT: 20px\" width=\"100\">QLD<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">5<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">22<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">1.025<\/td> <\/tr> <tr> <td style=\"HEIGHT: 20px\" width=\"100\">NSW<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">5<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">20<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">1.770<\/td> <\/tr> <tr> <td style=\"HEIGHT: 20px\" width=\"100\">WA<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">5<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">18<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">1.072<\/td> <\/tr> <tr> <td style=\"HEIGHT: 20px\" width=\"100\">VIC<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">5<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">12<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">0.865<\/td> <\/tr> <tr> <td style=\"HEIGHT: 20px\" width=\"100\">TAS<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">5<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">6<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">0.812<\/td> <\/tr> <tr> <td style=\"HEIGHT: 20px\" width=\"100\">SA<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">5<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">6<\/td> <td style=\"HEIGHT: 20px\" width=\"100\">0.786<\/td> <\/tr> <\/tbody> <\/table><br xmlns:util=\"com.vignette.ri.common.util\" xmlns:commonutil=\"com.epicentric.contentmanagement.connectors.cda\" xmlns:java=\"http:\/\/xml.apache.org\/xslt\/java\"><ul><\/ul>\n";
testMarkup += "\n";
testMarkup += "            <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/tbody><\/table>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for Pura Cup Points Table 2004\/05 portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for ING Cup Points Table 2004\/05 portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome2\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>ING Cup Points Table<\/th>            \n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>                \n";
testMarkup += "<\/table>    \n";
testMarkup += "\n";
testMarkup += "    <table width=\"199\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "            <td valign=\"top\" width=\"199\" bgcolor=\"#ebebeb\">    \n";
testMarkup += "            \n";
testMarkup += "		<i>Current at Jan 3, 2005<\/i><br>\n";
testMarkup += "<table style=\"HEIGHT: 193px\" cellspacing=\"0\" cellpadding=\"0\" width=\"185\" align=\"center\" border=\"0\">\n";
testMarkup += "<tbody>\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\"><b>TEAM<\/b><\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\"><b>Mt<\/b><\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\"><b>Pts<\/b><\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\"><b>Net R\/R<\/b><\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">QLD<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">7<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">30<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">1.356<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">VIC<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">7<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">18<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">0.477<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">TAS<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">7<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">18<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">-0.263<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">WA<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">6<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">12<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">-0.247<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">NSW<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">6<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">8<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">-0.098<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">SA<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">7<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">4<\/td>\n";
testMarkup += "<td style=\"HEIGHT: 20px\" width=\"100\">-1.240<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "<\/tbody>\n";
testMarkup += "<\/table>\n";
testMarkup += "<br xmlns:util=\"com.vignette.ri.common.util\" xmlns:commonutil=\"com.epicentric.contentmanagement.connectors.cda\" xmlns:java=\"http:\/\/xml.apache.org\/xslt\/java\"><ul><\/ul>\n";
testMarkup += "\n";
testMarkup += "            <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/tbody><\/table>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for ING Cup Points Table 2004\/05 portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for WNCL Points Table 3 portlet - start -->\n";
testMarkup += "\n";
testMarkup += "<table cellspacing=\"0\" class=\"tableHome2\" width=\"100%\">\n";
testMarkup += "    <thead>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <th>WNCL Points Table<\/th>           \n ";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/thead>                \n";
testMarkup += "<\/table>    \n";
testMarkup += "\n";
testMarkup += "    <table width=\"199\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n";
testMarkup += "        <tbody><tr>\n";
testMarkup += "            <td valign=\"top\" width=\"199\" bgcolor=\"#ebebeb\">    \n";
testMarkup += "            \n";
testMarkup += "		<img xmlns:util=\"com.vignette.ri.common.util\" xmlns:commonutil=\"com.epicentric.contentmanagement.connectors.cda\" xmlns:java=\"http:\/\/xml.apache.org\/xslt\/java\" src=\"\/web\/20050105050831im_\/http:\/\/wic042cx.server-web.com\/Static%20Files\/Images\/img_spacer.gif\" alt=\".\"><br><i>Current at Nov&nbsp;24&nbsp;2004<\/i><br>\n";
testMarkup += "<table style=\"HEIGHT: 140px\" bordercolor=\"#000000\" width=\"100%\">\n";
testMarkup += "<tbody>\n";
testMarkup += "<tr>\n";
testMarkup += "<td><strong>&nbsp;Team<\/strong><\/td>\n";
testMarkup += "<td><strong>Mt&nbsp;<\/strong> <\/td>\n";
testMarkup += "<td><strong>Pts&nbsp;<\/strong> <\/td>\n";
testMarkup += "<td><strong>Net R\/R<\/strong><\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td>NSW<\/td>\n";
testMarkup += "<td>4<\/td>\n";
testMarkup += "<td>19<\/td>\n";
testMarkup += "<td>1.209<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td>VIC<\/td>\n";
testMarkup += "<td>4<\/td>\n";
testMarkup += "<td>19&nbsp;<\/td>\n";
testMarkup += "<td>1.065<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td>SA<\/td>\n";
testMarkup += "<td>4<\/td>\n";
testMarkup += "<td>6<\/td>\n";
testMarkup += "<td>-0.204<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td>QLD<\/td>\n";
testMarkup += "<td>4<\/td>\n";
testMarkup += "<td>2<\/td>\n";
testMarkup += "<td>-0.622<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "\n";
testMarkup += "<tr>\n";
testMarkup += "<td>WA<\/td>\n";
testMarkup += "<td>4<\/td>\n";
testMarkup += "<td>0<\/td>\n";
testMarkup += "<td>-1.666<\/td>\n";
testMarkup += "<\/tr>\n";
testMarkup += "<\/tbody>\n";
testMarkup += "<\/table>\n";
testMarkup += "<br><ul><\/ul>\n";
testMarkup += "\n";
testMarkup += "            <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "    <\/tbody><\/table>\n";
testMarkup += "   \n";
testMarkup += "<!-- Chrome (Drk Green \/ Namable) portlet chrome for WNCL Points Table 3 portlet - end -->\n";
testMarkup += "\n";
testMarkup += "                <br>\n";
testMarkup += "   \n";
testMarkup += "          <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "      <\/tbody><\/table>\n";
testMarkup += "    <\/td>\n";
testMarkup += "\n";
testMarkup += "  <\/tr>\n";
testMarkup += "\n";
testMarkup += "    <tr>\n";
testMarkup += "\n";
testMarkup += "      <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/images\/misc\/spacer.gif\" width=\"85\" height=\"1\" border=\"0\" alt=\"\">\n";
testMarkup += "      <\/td>\n";
testMarkup += "\n";
testMarkup += "      <td><img src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/images\/misc\/spacer.gif\" width=\"15\" height=\"1\" border=\"0\" alt=\"\">\n";
testMarkup += "      <\/td>\n";
testMarkup += "\n";
testMarkup += "    <\/tr>\n";
testMarkup += "\n";
testMarkup += "<\/tbody><\/table>\n";
testMarkup += "\n";
testMarkup += "            <\/td>\n";
testMarkup += "        <\/tr>\n";
testMarkup += "        <tr>\n";
testMarkup += "            <td height=\"18\" valign=\"top\">\n";
testMarkup += "                &nbsp;&nbsp;&nbsp;<a href=\"#top\"><img alt=\"Top\" height=\"18\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/cricket_images_www\/images\/img_top.gif\" width=\"24\" align=\"absmiddle\" border=\"0\">Back to Top<\/a><br><br>\n";
testMarkup += "            <\/td>\n";
testMarkup += "        <\/tr>         \n";
testMarkup += "        <\/tbody><\/table>    \n";
testMarkup += "    <\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "<\/tbody><\/table>\n";
testMarkup += "<table id=\"footer\" cellspacing=\"0\" border=\"0\">\n";
testMarkup += "   <tbody><tr>\n";
testMarkup += "    <td><img height=\"17\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/templates\/YbSacRfaWQTWdeWeWZRYdWRQUUSQaSaQ\/VRQRZWURaaaZTfWeWZRYdWRQUUSQaSaQ\/img_footer_left.jpg\" width=\"250\"><\/td>";
testMarkup += "    <td align=\"center\" width=\"100%\">    \n";
testMarkup += "    <a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.4a871880c089f6ed371ae9104420a2a0\/\">home<\/a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.29e17ed5bfc147ed371ae9104420a2a0\/\">Terms of use<\/a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"\/web\/20050105050831\/http:\/\/www.cricket.com.au\/portal\/site\/cricketaustralia\/menuitem.7abeff5bc8a447ed371ae9104420a2a0\/\">Privacy<\/a>\n";
testMarkup += "    <\/td>\n";
testMarkup += "    <td><img height=\"17\" src=\"\/web\/20050105050831im_\/http:\/\/www.cricket.com.au\/portal\/templates\/YbSacRfaWQTWdeWeWZRYdWRQUUSQaSaQ\/VRQRZWURaaaZTfWeWZRYdWRQUUSQaSaQ\/img_footer_right.jpg\" width=\"250\"><\/td>\n";
testMarkup += "   <\/tr>\n";
testMarkup += "<\/tbody><\/table>\n";


  
  function setupEditor () {
    aceEditor = ace.edit("editor");
    aceEditor.setShowPrintMargin(false);
    aceEditor.getSession().setUseWorker(false);
    aceEditor.getSession().setMode("ace/mode/html");
    aceEditor.getSession().on('change', updatePreview);
    aceEditor.setValue(testMarkup);
  }
  
  function setupCssEditor () {
  	aceEditor = ace.edit("csseditor");
    aceEditor.setShowPrintMargin(false);
    aceEditor.getSession().setUseWorker(false);
    aceEditor.getSession().setMode("ace/mode/css");
    aceEditor.getSession().on('change', updateCssPreview);
    aceEditor.setValue(testMarkup);
  }


  function updatePreview () {
    var editorContent = aceEditor.getSession().getValue();
    $preview.contents().find('body').html(editorContent);
  }

  function updateCssPreview () {
  	var editorContent = aceEditor.getSession().getValue();
  	$preview.contents().find('body').css(editorContent);
  }


  setupEditor();
  setupCssEditor();



  $(window).trigger('resize');
}());